// Mocks generated by Mockito 5.4.1 from annotations
// in tasks_flutter_one/test/widget/login/task_login_signup_widget_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_login/contract/login_contract.dart' as _i2;
import 'package:tasks_core/base_provider.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginPresenter extends _i1.Mock implements _i2.LoginPresenter {
  @override
  void navigateToCreateAccountPage(dynamic context) => super.noSuchMethod(
        Invocation.method(
          #navigateToCreateAccountPage,
          [context],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void navigateToLoginSignUp(dynamic context) => super.noSuchMethod(
        Invocation.method(
          #navigateToLoginSignUp,
          [context],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void navigateToHomePage(dynamic context) => super.noSuchMethod(
        Invocation.method(
          #navigateToHomePage,
          [context],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void closeApp(dynamic context) => super.noSuchMethod(
        Invocation.method(
          #closeApp,
          [context],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void navigateToLoginSignInPage(dynamic context) => super.noSuchMethod(
        Invocation.method(
          #navigateToLoginSignInPage,
          [context],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void showMessageFeedBack(
    dynamic context,
    String? message,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showMessageFeedBack,
          [
            context,
            message,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void registerAccount(
    String? email,
    String? password,
    bool? rememberEmail,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #registerAccount,
          [
            email,
            password,
            rememberEmail,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void signUpAccount(
    String? email,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #signUpAccount,
          [
            email,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setProvider(_i3.BaseProvider? baseProvider) => super.noSuchMethod(
        Invocation.method(
          #setProvider,
          [baseProvider],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoginView].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginView extends _i1.Mock implements _i2.LoginView {
  @override
  void closeApp() => super.noSuchMethod(
        Invocation.method(
          #closeApp,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearInputs() => super.noSuchMethod(
        Invocation.method(
          #clearInputs,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void navigateToHome() => super.noSuchMethod(
        Invocation.method(
          #navigateToHome,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic showError(String? message) => super.noSuchMethod(
        Invocation.method(
          #showError,
          [message],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic showMessage(String? message) => super.noSuchMethod(
        Invocation.method(
          #showMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic showOrHideLoading(bool? flag) => super.noSuchMethod(
        Invocation.method(
          #showOrHideLoading,
          [flag],
        ),
        returnValueForMissingStub: null,
      );
}
