// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8KUBQJQ3UMa5XVZTGQWhksi7TuvgLnts',
    appId: '1:413849803669:web:0ee6b96355e92dad6eb49c',
    messagingSenderId: '413849803669',
    projectId: 'firstprojectinfnet',
    authDomain: 'firstprojectinfnet.firebaseapp.com',
    databaseURL: 'https://firstprojectinfnet-default-rtdb.firebaseio.com',
    storageBucket: 'firstprojectinfnet.appspot.com',
    measurementId: 'G-L5CGCKKQT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC28SaU6-jD_bidg3PGF1ghdyY4eQIKvvk',
    appId: '1:413849803669:android:87771079e21bb9856eb49c',
    messagingSenderId: '413849803669',
    projectId: 'firstprojectinfnet',
    databaseURL: 'https://firstprojectinfnet-default-rtdb.firebaseio.com',
    storageBucket: 'firstprojectinfnet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUik8MdhCSTm0MwFQBTbmqj0LOnP0oN8w',
    appId: '1:413849803669:ios:dacdebfdd613e09b6eb49c',
    messagingSenderId: '413849803669',
    projectId: 'firstprojectinfnet',
    databaseURL: 'https://firstprojectinfnet-default-rtdb.firebaseio.com',
    storageBucket: 'firstprojectinfnet.appspot.com',
    androidClientId:
    '413849803669-d8uofvqh8tptbfnn5k7v0m1tho6oi7ch.apps.googleusercontent.com',
    iosClientId:
    '413849803669-dj41vp5une2khdso1tju7v0lnaueq1ad.apps.googleusercontent.com',
    iosBundleId: 'com.infnet.task.tasksFlutterOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUik8MdhCSTm0MwFQBTbmqj0LOnP0oN8w',
    appId: '1:413849803669:ios:caf960e403ac24d06eb49c',
    messagingSenderId: '413849803669',
    projectId: 'firstprojectinfnet',
    databaseURL: 'https://firstprojectinfnet-default-rtdb.firebaseio.com',
    storageBucket: 'firstprojectinfnet.appspot.com',
    androidClientId:
    '413849803669-d8uofvqh8tptbfnn5k7v0m1tho6oi7ch.apps.googleusercontent.com',
    iosClientId:
    '413849803669-ioo55qho4c26ghoqqm9eh01rg3ng6k5o.apps.googleusercontent.com',
    iosBundleId: 'com.infnet.task.tasksFlutterOne.RunnerTests',
  );
}