// Mocks generated by Mockito 5.4.1 from annotations
// in tasks_flutter_one/test/unit/weather/weather_api_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tasks_core/core/data/model/weather_data_model.dart' as _i2;
import 'package:tasks_flutter_one/features/home/data/datasource/home_task_weather_datasource.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCurrentWeather_0 extends _i1.SmartFake
    implements _i2.CurrentWeather {
  _FakeCurrentWeather_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i3.WeatherRemoteDataSource {
  @override
  _i4.Future<_i2.CurrentWeather> getWeatherCurrentData(
    double? lat,
    double? long,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherCurrentData,
          [
            lat,
            long,
          ],
        ),
        returnValue: _i4.Future<_i2.CurrentWeather>.value(_FakeCurrentWeather_0(
          this,
          Invocation.method(
            #getWeatherCurrentData,
            [
              lat,
              long,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.CurrentWeather>.value(_FakeCurrentWeather_0(
          this,
          Invocation.method(
            #getWeatherCurrentData,
            [
              lat,
              long,
            ],
          ),
        )),
      ) as _i4.Future<_i2.CurrentWeather>);
}
